#include <string.h>
#include <stdlib.h>
#include "utility.h"

int getTokenId(char * s){
	if(!strcmp(s,"EMPTY")) return 0;
	if(!strcmp(s,"PLUS")) return 1;
	if(!strcmp(s,"MINUS")) return 2;
	if(!strcmp(s,"MUL")) return 3;
	if(!strcmp(s,"DIV")) return 4;
	if(!strcmp(s,"COMMA")) return 5;
	if(!strcmp(s,"SEMICOL")) return 6;
	if(!strcmp(s,"SQBO")) return 7;
	if(!strcmp(s,"SQBC")) return 8;
	if(!strcmp(s,"BO")) return 9;
	if(!strcmp(s,"BC")) return 10;
	if(!strcmp(s,"EQ")) return 11;
	if(!strcmp(s,"NE")) return 12;
	if(!strcmp(s,"ASSIGNOP")) return 13;
	if(!strcmp(s,"COLON")) return 14;
	if(!strcmp(s,"LE")) return 15;
	if(!strcmp(s,"DEF")) return 16;
	if(!strcmp(s,"LT")) return 17;
	if(!strcmp(s,"GE")) return 18;
	if(!strcmp(s,"ENDDEF")) return 19;
	if(!strcmp(s,"GT")) return 20;
	if(!strcmp(s,"NUM")) return 21;
	if(!strcmp(s,"RANGEOP")) return 22;
	if(!strcmp(s,"RNUM")) return 23;
	if(!strcmp(s,"INTEGER")) return 24;
	if(!strcmp(s,"REAL")) return 25;
	if(!strcmp(s,"BOOLEAN")) return 26;
	if(!strcmp(s,"OF")) return 27;
	if(!strcmp(s,"ARRAY")) return 28;
	if(!strcmp(s,"START")) return 29;
	if(!strcmp(s,"END")) return 30;
	if(!strcmp(s,"DECLARE")) return 31;
	if(!strcmp(s,"MODULE")) return 32;
	if(!strcmp(s,"DRIVER")) return 33;
	if(!strcmp(s,"PROGRAM")) return 34;
	if(!strcmp(s,"GET_VALUE")) return 35;
	if(!strcmp(s,"PRINT")) return 36;
	if(!strcmp(s,"USE")) return 37;
	if(!strcmp(s,"WITH")) return 38;
	if(!strcmp(s,"PARAMETERS")) return 39;
	if(!strcmp(s,"TRUE")) return 40;
	if(!strcmp(s,"FALSE")) return 41;
	if(!strcmp(s,"TAKES")) return 42;
	if(!strcmp(s,"INPUT")) return 43;
	if(!strcmp(s,"RETURNS")) return 44;
	if(!strcmp(s,"AND")) return 45;
	if(!strcmp(s,"OR")) return 46;
	if(!strcmp(s,"FOR")) return 47;
	if(!strcmp(s,"IN")) return 48;
	if(!strcmp(s,"SWITCH")) return 49;
	if(!strcmp(s,"CASE")) return 50;
	if(!strcmp(s,"BREAK")) return 51;
	if(!strcmp(s,"DEFAULT")) return 52;
	if(!strcmp(s,"WHILE")) return 53;
	if(!strcmp(s,"ID")) return 54;
	if(!strcmp(s,"DRIVERDEF")) return 55;
	if(!strcmp(s,"DRIVERENDDEF")) return 56;
	if(!strcmp(s,"$")) return 57;
	if(!strcmp(s,"AnyTerm")) return 101;
	if(!strcmp(s,"N1")) return 102;
	if(!strcmp(s,"N2")) return 103;
	if(!strcmp(s,"N3")) return 104;
	if(!strcmp(s,"N4")) return 105;
	if(!strcmp(s,"N5")) return 106;
	if(!strcmp(s,"N7")) return 107;
	if(!strcmp(s,"N8")) return 108;
	if(!strcmp(s,"N9")) return 109;
	if(!strcmp(s,"arithmeticExpr")) return 110;
	if(!strcmp(s,"arithmeticOrBooleanExpr")) return 111;
	if(!strcmp(s,"assignmentStmt")) return 112;
	if(!strcmp(s,"caseStmts")) return 113;
	if(!strcmp(s,"conditionalStmt")) return 114;
	if(!strcmp(s,"dataType")) return 115;
	if(!strcmp(s,"declareStmt")) return 116;
	if(!strcmp(s,"default")) return 117;
	if(!strcmp(s,"driverModule")) return 118;
	if(!strcmp(s,"expression")) return 119;
	if(!strcmp(s,"factor")) return 120;
	if(!strcmp(s,"idList")) return 121;
	if(!strcmp(s,"index")) return 122;
	if(!strcmp(s,"input_plist")) return 123;
	if(!strcmp(s,"ioStmt")) return 124;
	if(!strcmp(s,"iterativeStmt")) return 125;
	if(!strcmp(s,"logicalOp")) return 126;
	if(!strcmp(s,"lvalueARRStmt")) return 127;
	if(!strcmp(s,"lvalueIDStmt")) return 128;
	if(!strcmp(s,"module")) return 129;
	if(!strcmp(s,"moduleDeclaration")) return 130;
	if(!strcmp(s,"moduleDeclarations")) return 131;
	if(!strcmp(s,"moduleDef")) return 132;
	if(!strcmp(s,"moduleReuseStmt")) return 133;
	if(!strcmp(s,"op1")) return 134;
	if(!strcmp(s,"op2")) return 135;
	if(!strcmp(s,"optional")) return 136;
	if(!strcmp(s,"otherModules")) return 137;
	if(!strcmp(s,"output_plist")) return 138;
	if(!strcmp(s,"program")) return 139;
	if(!strcmp(s,"range")) return 140;
	if(!strcmp(s,"relationalOp")) return 141;
	if(!strcmp(s,"ret")) return 142;
	if(!strcmp(s,"simpleStmt")) return 143;
	if(!strcmp(s,"statement")) return 144;
	if(!strcmp(s,"statements")) return 145;
	if(!strcmp(s,"term")) return 146;
	if(!strcmp(s,"type")) return 147;
	if(!strcmp(s,"value")) return 148;
	if(!strcmp(s,"var")) return 149;
	if(!strcmp(s,"whichId")) return 150;
	if(!strcmp(s,"whichStmt")) return 151;
	return -1;
}

void idtotk(int n){
	if(n==0) printf("EMPTY");
	if(n==1) printf("PLUS");
	if(n==2) printf("MINUS");
	if(n==3) printf("MUL");
	if(n==4) printf("DIV");
	if(n==5) printf("COMMA");
	if(n==6) printf("SEMICOL");
	if(n==7) printf("SQBO");
	if(n==8) printf("SQBC");
	if(n==9) printf("BO");
	if(n==10) printf("BC");
	if(n==11) printf("EQ");
	if(n==12) printf("NE");
	if(n==13) printf("ASSIGNOP");
	if(n==14) printf("COLON");
	if(n==15) printf("LE");
	if(n==16) printf("DEF");
	if(n==17) printf("LT");
	if(n==18) printf("GE");
	if(n==19) printf("ENDDEF");
	if(n==20) printf("GT");
	if(n==21) printf("NUM");
	if(n==22) printf("RANGEOP");
	if(n==23) printf("RNUM");
	if(n==24) printf("INTEGER");
	if(n==25) printf("REAL");
	if(n==26) printf("BOOLEAN");
	if(n==27) printf("OF");
	if(n==28) printf("ARRAY");
	if(n==29) printf("START");
	if(n==30) printf("END");
	if(n==31) printf("DECLARE");
	if(n==32) printf("MODULE");
	if(n==33) printf("DRIVER");
	if(n==34) printf("PROGRAM");
	if(n==35) printf("GET_VALUE");
	if(n==36) printf("PRINT");
	if(n==37) printf("USE");
	if(n==38) printf("WITH");
	if(n==39) printf("PARAMETERS");
	if(n==40) printf("TRUE");
	if(n==41) printf("FALSE");
	if(n==42) printf("TAKES");
	if(n==43) printf("INPUT");
	if(n==44) printf("RETURNS");
	if(n==45) printf("AND");
	if(n==46) printf("OR");
	if(n==47) printf("FOR");
	if(n==48) printf("IN");
	if(n==49) printf("SWITCH");
	if(n==50) printf("CASE");
	if(n==51) printf("BREAK");
	if(n==52) printf("DEFAULT");
	if(n==53) printf("WHILE");
	if(n==54) printf("ID");
	if(n==55) printf("DRIVERDEF");
	if(n==56) printf("DRIVERENDDEF");
	if(n==57) printf("$");
	if(n==101) printf("anyterm");
	if(n==102) printf("N1");
	if(n==103) printf("N2");
	if(n==104) printf("N3");
	if(n==105) printf("N4");
	if(n==106) printf("N5");
	if(n==107) printf("N7");
	if(n==108) printf("N8");
	if(n==109) printf("N9");
	if(n==110) printf("arithmeticExpr");
	if(n==111) printf("arithmeticOrBooleanExpr");
	if(n==112) printf("assignmentStmt");
	if(n==113) printf("caseStmts");
	if(n==114) printf("conditionalStmt");
	if(n==115) printf("dataType");
	if(n==116) printf("declareStmt");
	if(n==117) printf("default");
	if(n==118) printf("driverModule");
	if(n==119) printf("expression");
	if(n==120) printf("factor");
	if(n==121) printf("idList");
	if(n==122) printf("index");
	if(n==123) printf("input_plist");
	if(n==124) printf("ioStmt");
	if(n==125) printf("iterativeStmt");
	if(n==126) printf("logicalOp");
	if(n==127) printf("lvalueARRStmt");
	if(n==128) printf("lvalueIDStmt");
	if(n==129) printf("module");
	if(n==130) printf("moduleDeclaration");
	if(n==131) printf("moduleDeclarations");
	if(n==132) printf("modueDef");
	if(n==133) printf("moduleReuseStmt");
	if(n==134) printf("op1");
	if(n==135) printf("op2");
	if(n==136) printf("optional");
	if(n==137) printf("otherModules");
	if(n==138) printf("output_plist");
	if(n==139) printf("program");
	if(n==140) printf("range");
	if(n==141) printf("relationalOp");
	if(n==142) printf("ret");
	if(n==143) printf("simpleStmt");
	if(n==144) printf("statement");
	if(n==145) printf("statements");
	if(n==146) printf("term");
	if(n==147) printf("type");
	if(n==148) printf("value");
	if(n==149) printf("var");
	if(n==150) printf("whichId");
	if(n==151) printf("whichStmt");
}

char * idtotkstr(int n){
	if(n==0  ) return("EMPTY");
	if(n==1  ) return("PLUS");
	if(n==2  ) return("MINUS");
	if(n==3  ) return("MUL");
	if(n==4  ) return("DIV");
	if(n==5  ) return("COMMA");
	if(n==6  ) return("SEMICOL");
	if(n==7  ) return("SQBO");
	if(n==8  ) return("SQBC");
	if(n==9  ) return("BO");
	if(n==10 ) return("BC");
	if(n==11 ) return("EQ");
	if(n==12 ) return("NE");
	if(n==13 ) return("ASSIGNOP");
	if(n==14 ) return("COLON");
	if(n==15 ) return("LE");
	if(n==16 ) return("DEF");
	if(n==17 ) return("LT");
	if(n==18 ) return("GE");
	if(n==19 ) return("ENDDEF");
	if(n==20 ) return("GT");
	if(n==21 ) return("NUM");
	if(n==22 ) return("RANGEOP");
	if(n==23 ) return("RNUM");
	if(n==24 ) return("INTEGER");
	if(n==25 ) return("REAL");
	if(n==26 ) return("BOOLEAN");
	if(n==27 ) return("OF");
	if(n==28 ) return("ARRAY");
	if(n==29 ) return("START");
	if(n==30 ) return("END");
	if(n==31 ) return("DECLARE");
	if(n==32 ) return("MODULE");
	if(n==33 ) return("DRIVER");
	if(n==34 ) return("PROGRAM");
	if(n==35 ) return("GET_VALUE");
	if(n==36 ) return("PRINT");
	if(n==37 ) return("USE");
	if(n==38 ) return("WITH");
	if(n==39 ) return("PARAMETERS");
	if(n==40 ) return("TRUE");
	if(n==41 ) return("FALSE");
	if(n==42 ) return("TAKES");
	if(n==43 ) return("INPUT");
	if(n==44 ) return("RETURNS");
	if(n==45 ) return("AND");
	if(n==46 ) return("OR");
	if(n==47 ) return("FOR");
	if(n==48 ) return("IN");
	if(n==49 ) return("SWITCH");
	if(n==50 ) return("CASE");
	if(n==51 ) return("BREAK");
	if(n==52 ) return("DEFAULT");
	if(n==53 ) return("WHILE");
	if(n==54 ) return("ID");
	if(n==55 ) return("DRIVERDEF");
	if(n==56 ) return("DRIVERENDDEF");
	if(n==57 ) return("$");
	if(n==101) return("anyterm");
	if(n==102) return("N1");
	if(n==103) return("N2");
	if(n==104) return("N3");
	if(n==105) return("N4");
	if(n==106) return("N5");
	if(n==107) return("N7");
	if(n==108) return("N8");
	if(n==109) return("N9");
	if(n==110) return("arithmeticExpr");
	if(n==111) return("arithmeticOrBooleanExpr");
	if(n==112) return("assignmentStmt");
	if(n==113) return("caseStmts");
	if(n==114) return("conditionalStmt");
	if(n==115) return("dataType");
	if(n==116) return("declareStmt");
	if(n==117) return("default");
	if(n==118) return("driverModule");
	if(n==119) return("expression");
	if(n==120) return("factor");
	if(n==121) return("idList");
	if(n==122) return("index");
	if(n==123) return("input_plist");
	if(n==124) return("ioStmt");
	if(n==125) return("iterativeStmt");
	if(n==126) return("logicalOp");
	if(n==127) return("lvalueARRStmt");
	if(n==128) return("lvalueIDStmt");
	if(n==129) return("module");
	if(n==130) return("moduleDeclaration");
	if(n==131) return("moduleDeclarations");
	if(n==132) return("modueDef");
	if(n==133) return("moduleReuseStmt");
	if(n==134) return("op1");
	if(n==135) return("op2");
	if(n==136) return("optional");
	if(n==137) return("otherModules");
	if(n==138) return("output_plist");
	if(n==139) return("program");
	if(n==140) return("range");
	if(n==141) return("relationalOp");
	if(n==142) return("ret");
	if(n==143) return("simpleStmt");
	if(n==144) return("statement");
	if(n==145) return("statements");
	if(n==146) return("term");
	if(n==147) return("type");
	if(n==148) return("value");
	if(n==149) return("var");
	if(n==150) return("whichId");
	if(n==151) return("whichStmt");
}